export const STRUCTURES_PARTENAIRES = [
  'Fondation du Prado',
  'Prado Itinéraires',
  'Prado — Maison d\'Enfants',
  'Prado — Service de Milieu Ouvert',
  'Prado — Service d\'Accueil Familial',
  'Département du Rhône — ASE',
  'Département de l\'Ain — ASE',
  'Département de l\'Isère — ASE',
  'Métropole de Lyon — Prévention Spécialisée',
  'PJJ — STEMO Rhône',
  'PJJ — UEAJ Lyon',
  'Mission Locale de Lyon',
  'Mission Locale Villeurbanne',
  'CAF du Rhône',
  'DDETS du Rhône',
  'ADAPEI du Rhône',
  'ADSEA du Rhône',
  'Sauvegarde 69',
  'OVE — Œuvre des Villages d\'Enfants',
  'SOS Villages d\'Enfants',
  'Croix-Rouge — Rhône',
  'Apprentis d\'Auteuil — Rhône-Alpes',
  'MECS Les Alizés',
  'MECS Le Château',
  'Foyer de l\'Enfance du Rhône',
  'ITEP — Institut Thérapeutique Éducatif et Pédagogique',
  'IME — Institut Médico-Éducatif',
  'SESSAD',
  'Centre Social — Lyon',
  'Centre Social — Villeurbanne',
  'Maison des Adolescents — Lyon',
  'Point Accueil Écoute Jeunes',
  'Résidence Habitat Jeunes',
]
