// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Blog — Actualite documents
 */
interface ActualiteDocumentData {
	/**
	 * Titre field in *Blog — Actualite*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: actualite.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Extrait field in *Blog — Actualite*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: actualite.excerpt
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	excerpt: prismic.KeyTextField;
	
	/**
	 * Date field in *Blog — Actualite*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: actualite.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;
	
	/**
	 * Image field in *Blog — Actualite*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: actualite.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Contenu field in *Blog — Actualite*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: actualite.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
}

/**
 * Blog — Actualite document from Prismic
 *
 * - **API ID**: `actualite`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActualiteDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ActualiteDocumentData>, "actualite", Lang>;

/**
 * Content for Document documents
 */
interface DocumentDocumentData {
	/**
	 * Titre field in *Document*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: document.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *Document*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: document.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Catégorie field in *Document*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: document.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	category: prismic.SelectField<"Catalogue" | "Rapport" | "Guide" | "Autre">;
	
	/**
	 * Fichier PDF field in *Document*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: document.file
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	file: prismic.LinkToMediaField<prismic.FieldState, never>;
	
	/**
	 * Image de couverture field in *Document*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: document.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Document document from Prismic
 *
 * - **API ID**: `document`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocumentDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<DocumentDocumentData>, "document", Lang>;

/**
 * Content for Educolab documents
 */
interface EducolabDocumentData {
	/**
	 * Sur-titre field in *Educolab*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Competences parentales
	 * - **API ID Path**: educolab.surtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	surtitle: prismic.KeyTextField;
	
	/**
	 * Titre field in *Educolab*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Image hero field in *Educolab*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Couleur dominante field in *Educolab*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.brand_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	brand_color: prismic.ColorField;
	
	/**
	 * Titre de la carte field in *Educolab*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.card_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	card_title: prismic.KeyTextField;
	
	/**
	 * Contenu de la carte field in *Educolab*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.card_body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	card_body: prismic.RichTextField;
	
	/**
	 * Texte du bouton field in *Educolab*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.cta_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * Lien externe field in *Educolab*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.cta_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;/**
	 * Meta Title field in *Educolab*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Educolab*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: educolab.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
}

/**
 * Educolab document from Prismic
 *
 * - **API ID**: `educolab`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EducolabDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<EducolabDocumentData>, "educolab", Lang>;

/**
 * Item in *Foodtruck → Points forts*
 */
export interface FoodtruckDocumentDataHighlightsItem {
	/**
	 * Icone field in *Foodtruck → Points forts*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.highlights[].icon_name
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	icon_name: prismic.SelectField<"ChefHat" | "Users" | "Heart" | "Truck" | "Utensils">;
	
	/**
	 * Libelle field in *Foodtruck → Points forts*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.highlights[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Description field in *Foodtruck → Points forts*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.highlights[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
}

/**
 * Item in *Foodtruck → Planning de tournee*
 */
export interface FoodtruckDocumentDataTourneeItem {
	/**
	 * Jour field in *Foodtruck → Planning de tournee*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.tournee[].jour
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	jour: prismic.KeyTextField;
	
	/**
	 * Lieu field in *Foodtruck → Planning de tournee*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.tournee[].lieu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	lieu: prismic.KeyTextField;
	
	/**
	 * Precision (frequence) field in *Foodtruck → Planning de tournee*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.tournee[].precision
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	precision: prismic.KeyTextField;
}

/**
 * Item in *Foodtruck → Entrees*
 */
export interface FoodtruckDocumentDataEntreesItem {
	/**
	 * Nom field in *Foodtruck → Entrees*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.entrees[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Description / ingredients field in *Foodtruck → Entrees*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.entrees[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
}

/**
 * Item in *Foodtruck → Plats*
 */
export interface FoodtruckDocumentDataPlatsItem {
	/**
	 * Nom du plat field in *Foodtruck → Plats*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.plats[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Description / ingredients field in *Foodtruck → Plats*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.plats[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
}

/**
 * Item in *Foodtruck → Desserts*
 */
export interface FoodtruckDocumentDataDessertsItem {
	/**
	 * Nom field in *Foodtruck → Desserts*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.desserts[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Description / ingredients field in *Foodtruck → Desserts*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.desserts[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
}

/**
 * Item in *Foodtruck → Etapes d'inscription*
 */
export interface FoodtruckDocumentDataStepsItem {
	/**
	 * Numero field in *Foodtruck → Etapes d'inscription*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 01
	 * - **API ID Path**: foodtruck.steps[].step_number
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	step_number: prismic.KeyTextField;
	
	/**
	 * Titre field in *Foodtruck → Etapes d'inscription*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.steps[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *Foodtruck → Etapes d'inscription*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.steps[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
	
	/**
	 * Couleur field in *Foodtruck → Etapes d'inscription*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.steps[].color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	color: prismic.ColorField;
}

/**
 * Content for Foodtruck documents
 */
interface FoodtruckDocumentData {
	/**
	 * Sur-titre field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Foodtruck solidaire
	 * - **API ID Path**: foodtruck.surtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	surtitle: prismic.KeyTextField;
	
	/**
	 * Titre principal field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Accroche field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.tagline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tagline: prismic.KeyTextField;
	
	/**
	 * Image hero field in *Foodtruck*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Couleur dominante field in *Foodtruck*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.brand_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	brand_color: prismic.ColorField;
	
	/**
	 * Titre section projet field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.intro_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	intro_title: prismic.KeyTextField;
	
	/**
	 * Description du projet field in *Foodtruck*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.intro_body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	intro_body: prismic.RichTextField;/**
	 * Points forts field in *Foodtruck*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.highlights[]
	 * - **Tab**: Highlights
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	highlights: prismic.GroupField<Simplify<FoodtruckDocumentDataHighlightsItem>>;/**
	 * Planning de tournee field in *Foodtruck*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.tournee[]
	 * - **Tab**: Tournee
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tournee: prismic.GroupField<Simplify<FoodtruckDocumentDataTourneeItem>>;/**
	 * Titre section menu field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Menu du mois
	 * - **API ID Path**: foodtruck.menu_title
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	menu_title: prismic.KeyTextField;
	
	/**
	 * Sous-titre menu field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Menu de saison, a prix reduit. Mis a jour chaque mois.
	 * - **API ID Path**: foodtruck.menu_subtitle
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	menu_subtitle: prismic.KeyTextField;
	
	/**
	 * Citation menu (optionnel) field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: D'Lieb geht durich de Maawe
	 * - **API ID Path**: foodtruck.menu_quote
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	menu_quote: prismic.KeyTextField;
	
	/**
	 * Entrees field in *Foodtruck*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.entrees[]
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	entrees: prismic.GroupField<Simplify<FoodtruckDocumentDataEntreesItem>>;
	
	/**
	 * Plats field in *Foodtruck*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.plats[]
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	plats: prismic.GroupField<Simplify<FoodtruckDocumentDataPlatsItem>>;
	
	/**
	 * Desserts field in *Foodtruck*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.desserts[]
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	desserts: prismic.GroupField<Simplify<FoodtruckDocumentDataDessertsItem>>;
	
	/**
	 * Prix solidaire — Menu field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 9
	 * - **API ID Path**: foodtruck.prix_solidaire_menu
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	prix_solidaire_menu: prismic.KeyTextField;
	
	/**
	 * Prix solidaire — Plat field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 6
	 * - **API ID Path**: foodtruck.prix_solidaire_plat
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	prix_solidaire_plat: prismic.KeyTextField;
	
	/**
	 * Prix solidaire — Dessert/Entree field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 3
	 * - **API ID Path**: foodtruck.prix_solidaire_dessert
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	prix_solidaire_dessert: prismic.KeyTextField;
	
	/**
	 * Prix normal — Menu field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 13
	 * - **API ID Path**: foodtruck.prix_normal_menu
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	prix_normal_menu: prismic.KeyTextField;
	
	/**
	 * Prix normal — Plat field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 8
	 * - **API ID Path**: foodtruck.prix_normal_plat
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	prix_normal_plat: prismic.KeyTextField;
	
	/**
	 * Prix normal — Dessert/Entree field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 3
	 * - **API ID Path**: foodtruck.prix_normal_dessert
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	prix_normal_dessert: prismic.KeyTextField;
	
	/**
	 * Note tarifs field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Boisson gratuite et a volonte
	 * - **API ID Path**: foodtruck.tarif_note
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tarif_note: prismic.KeyTextField;
	
	/**
	 * Libelle telephone field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Renseignements menus & tournees
	 * - **API ID Path**: foodtruck.phone_label
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_label: prismic.KeyTextField;
	
	/**
	 * Numeros de telephone field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 06 24 68 52 04 / 06 81 44 37 13
	 * - **API ID Path**: foodtruck.phone_numbers
	 * - **Tab**: Menu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_numbers: prismic.KeyTextField;/**
	 * Etapes d'inscription field in *Foodtruck*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.steps[]
	 * - **Tab**: Etapes
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	steps: prismic.GroupField<Simplify<FoodtruckDocumentDataStepsItem>>;/**
	 * Meta Title field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Foodtruck*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Foodtruck*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: foodtruck.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Foodtruck document from Prismic
 *
 * - **API ID**: `foodtruck`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FoodtruckDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FoodtruckDocumentData>, "foodtruck", Lang>;

/**
 * Item in *Fresque → Objectifs*
 */
export interface FresqueDocumentDataObjectivesItem {
	/**
	 * Icone field in *Fresque → Objectifs*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.objectives[].icon_name
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	icon_name: prismic.SelectField<"BookOpen" | "Lightbulb" | "Shield" | "Users" | "Heart">;
	
	/**
	 * Libelle field in *Fresque → Objectifs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.objectives[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Description field in *Fresque → Objectifs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.objectives[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
}

/**
 * Item in *Fresque → Parcours de vie*
 */
export interface FresqueDocumentDataParcoursItem {
	/**
	 * Nom et age field in *Fresque → Parcours de vie*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.parcours[].nom
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	nom: prismic.KeyTextField;
	
	/**
	 * Description field in *Fresque → Parcours de vie*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.parcours[].desc
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	desc: prismic.KeyTextField;
	
	/**
	 * Couleur field in *Fresque → Parcours de vie*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.parcours[].color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	color: prismic.ColorField;
}

/**
 * Item in *Fresque → Prochaines sessions*
 */
export interface FresqueDocumentDataSessionsItem {
	/**
	 * Date field in *Fresque → Prochaines sessions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.sessions[].date
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Version (Pro/Grand public) field in *Fresque → Prochaines sessions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.sessions[].version
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	version: prismic.KeyTextField;
	
	/**
	 * Lieu field in *Fresque → Prochaines sessions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.sessions[].lieu
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	lieu: prismic.KeyTextField;
	
	/**
	 * Duree field in *Fresque → Prochaines sessions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.sessions[].duree
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	duree: prismic.KeyTextField;
	
	/**
	 * Places restantes field in *Fresque → Prochaines sessions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.sessions[].places
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	places: prismic.KeyTextField;
}

/**
 * Content for Fresque documents
 */
interface FresqueDocumentData {
	/**
	 * Sur-titre field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Atelier pedagogique et collaboratif
	 * - **API ID Path**: fresque.surtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	surtitle: prismic.KeyTextField;
	
	/**
	 * Titre principal field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description courte (hero) field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Image hero field in *Fresque*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Couleur dominante field in *Fresque*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.brand_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	brand_color: prismic.ColorField;
	
	/**
	 * Titre section intro field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.intro_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	intro_title: prismic.KeyTextField;
	
	/**
	 * Texte d'introduction field in *Fresque*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.intro_body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	intro_body: prismic.RichTextField;
	
	/**
	 * Citation temoignage field in *Fresque*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.testimonial_quote
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	testimonial_quote: prismic.RichTextField;
	
	/**
	 * Auteur temoignage field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.testimonial_author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	testimonial_author: prismic.KeyTextField;/**
	 * Objectifs field in *Fresque*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.objectives[]
	 * - **Tab**: Objectifs
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	objectives: prismic.GroupField<Simplify<FresqueDocumentDataObjectivesItem>>;/**
	 * Parcours de vie field in *Fresque*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.parcours[]
	 * - **Tab**: Parcours
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	parcours: prismic.GroupField<Simplify<FresqueDocumentDataParcoursItem>>;/**
	 * Prochaines sessions field in *Fresque*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.sessions[]
	 * - **Tab**: Sessions
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	sessions: prismic.GroupField<Simplify<FresqueDocumentDataSessionsItem>>;/**
	 * Meta Title field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Fresque*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Fresque*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fresque.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Fresque document from Prismic
 *
 * - **API ID**: `fresque`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FresqueDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FresqueDocumentData>, "fresque", Lang>;

/**
 * Primary content in *Accueil → Slice Zone → Hero → Primary*
 */
export interface HomepageDocumentDataBodyHeroSlicePrimary {
	/**
	 * Sur-titre field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Association de la Fondation du Prado
	 * - **API ID Path**: homepage.body[].hero.primary.surtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	surtitle: prismic.KeyTextField;
	
	/**
	 * Titre principal field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].hero.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * CTA primaire - Texte field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].hero.primary.cta_primary_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_primary_label: prismic.KeyTextField;
	
	/**
	 * CTA primaire - Lien field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].hero.primary.cta_primary_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_primary_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * CTA secondaire - Texte field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].hero.primary.cta_secondary_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_secondary_label: prismic.KeyTextField;
	
	/**
	 * CTA secondaire - Lien field in *Accueil → Slice Zone → Hero → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].hero.primary.cta_secondary_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_secondary_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyHeroSlice = prismic.Slice<"hero", Simplify<HomepageDocumentDataBodyHeroSlicePrimary>, never>

/**
 * Primary content in *Accueil → Slice Zone → Programmes → Primary*
 */
export interface HomepageDocumentDataBodyProgrammesSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → Programmes → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → Programmes → Items*
 */
export interface HomepageDocumentDataBodyProgrammesSliceItem {
	/**
	 * Slug (ancre) field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: jeunes, foodtruck, etc.
	 * - **API ID Path**: homepage.body[].programmes.items.slug
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	slug: prismic.KeyTextField;
	
	/**
	 * Titre complet field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Titre court (sidebar) field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.short_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	short_title: prismic.KeyTextField;
	
	/**
	 * Icône field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.icon_name
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	icon_name: prismic.SelectField<"Users" | "Truck" | "Heart" | "BookOpen" | "UtensilsCrossed" | "HeartHandshake" | "Puzzle">;
	
	/**
	 * Couleur field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.brand_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	brand_color: prismic.ColorField;
	
	/**
	 * Description field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * CTA 1 - Texte field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.cta_1_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_1_label: prismic.KeyTextField;
	
	/**
	 * CTA 1 - Lien field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.cta_1_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_1_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * CTA 2 - Texte field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.cta_2_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_2_label: prismic.KeyTextField;
	
	/**
	 * CTA 2 - Lien field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.cta_2_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_2_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * CTA 3 - Texte field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.cta_3_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_3_label: prismic.KeyTextField;
	
	/**
	 * CTA 3 - Lien field in *Accueil → Slice Zone → Programmes → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].programmes.items.cta_3_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_3_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyProgrammesSlice = prismic.Slice<"programmes", Simplify<HomepageDocumentDataBodyProgrammesSlicePrimary>, Simplify<HomepageDocumentDataBodyProgrammesSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → Missions → Primary*
 */
export interface HomepageDocumentDataBodyMissionsSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → Missions → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].missions.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
	
	/**
	 * Texte d'introduction field in *Accueil → Slice Zone → Missions → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].missions.primary.intro_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	intro_text: prismic.RichTextField;
	
	/**
	 * Titre colonne jeunes field in *Accueil → Slice Zone → Missions → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].missions.primary.jeunes_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	jeunes_title: prismic.KeyTextField;
	
	/**
	 * Titre colonne familles field in *Accueil → Slice Zone → Missions → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].missions.primary.familles_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	familles_title: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → Missions → Items*
 */
export interface HomepageDocumentDataBodyMissionsSliceItem {
	/**
	 * Catégorie field in *Accueil → Slice Zone → Missions → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].missions.items.category
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	category: prismic.SelectField<"jeunes" | "familles">;
	
	/**
	 * Texte de la mission field in *Accueil → Slice Zone → Missions → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].missions.items.text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	text: prismic.KeyTextField;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyMissionsSlice = prismic.Slice<"missions", Simplify<HomepageDocumentDataBodyMissionsSlicePrimary>, Simplify<HomepageDocumentDataBodyMissionsSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → Chiffres d'impact → Primary*
 */
export interface HomepageDocumentDataBodyImpactSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → Chiffres d'impact → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].impact.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → Chiffres d'impact → Items*
 */
export interface HomepageDocumentDataBodyImpactSliceItem {
	/**
	 * Valeur numérique field in *Accueil → Slice Zone → Chiffres d'impact → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].impact.items.value
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	value: prismic.NumberField;
	
	/**
	 * Suffixe (+, %, etc.) field in *Accueil → Slice Zone → Chiffres d'impact → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].impact.items.suffix
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	suffix: prismic.KeyTextField;
	
	/**
	 * Libellé field in *Accueil → Slice Zone → Chiffres d'impact → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].impact.items.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Couleur field in *Accueil → Slice Zone → Chiffres d'impact → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].impact.items.color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	color: prismic.ColorField;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyImpactSlice = prismic.Slice<"impact", Simplify<HomepageDocumentDataBodyImpactSlicePrimary>, Simplify<HomepageDocumentDataBodyImpactSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → Étapes → Primary*
 */
export interface HomepageDocumentDataBodyStepsSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → Étapes → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].steps.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
	
	/**
	 * CTA - Texte field in *Accueil → Slice Zone → Étapes → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].steps.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA - Lien field in *Accueil → Slice Zone → Étapes → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].steps.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Texte de réassurance field in *Accueil → Slice Zone → Étapes → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].steps.primary.reassurance_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	reassurance_text: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → Étapes → Items*
 */
export interface HomepageDocumentDataBodyStepsSliceItem {
	/**
	 * Numéro field in *Accueil → Slice Zone → Étapes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 01
	 * - **API ID Path**: homepage.body[].steps.items.step_number
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	step_number: prismic.KeyTextField;
	
	/**
	 * Titre field in *Accueil → Slice Zone → Étapes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].steps.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *Accueil → Slice Zone → Étapes → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].steps.items.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyStepsSlice = prismic.Slice<"steps", Simplify<HomepageDocumentDataBodyStepsSlicePrimary>, Simplify<HomepageDocumentDataBodyStepsSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → Témoignages → Primary*
 */
export interface HomepageDocumentDataBodyTestimonialsSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → Témoignages → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].testimonials.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → Témoignages → Items*
 */
export interface HomepageDocumentDataBodyTestimonialsSliceItem {
	/**
	 * Citation field in *Accueil → Slice Zone → Témoignages → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].testimonials.items.quote
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	quote: prismic.RichTextField;
	
	/**
	 * Nom field in *Accueil → Slice Zone → Témoignages → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].testimonials.items.author_name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author_name: prismic.KeyTextField;
	
	/**
	 * Rôle field in *Accueil → Slice Zone → Témoignages → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].testimonials.items.author_role
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author_role: prismic.KeyTextField;
	
	/**
	 * Organisation field in *Accueil → Slice Zone → Témoignages → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].testimonials.items.author_org
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author_org: prismic.KeyTextField;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyTestimonialsSlice = prismic.Slice<"testimonials", Simplify<HomepageDocumentDataBodyTestimonialsSlicePrimary>, Simplify<HomepageDocumentDataBodyTestimonialsSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → FAQ → Primary*
 */
export interface HomepageDocumentDataBodyFaqSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → FAQ → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].faq.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → FAQ → Items*
 */
export interface HomepageDocumentDataBodyFaqSliceItem {
	/**
	 * Question field in *Accueil → Slice Zone → FAQ → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].faq.items.question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Réponse field in *Accueil → Slice Zone → FAQ → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].faq.items.answer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	answer: prismic.RichTextField;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyFaqSlice = prismic.Slice<"faq", Simplify<HomepageDocumentDataBodyFaqSlicePrimary>, Simplify<HomepageDocumentDataBodyFaqSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → Partenaires → Primary*
 */
export interface HomepageDocumentDataBodyPartnersSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → Partenaires → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].partners.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
	
	/**
	 * Sous-titre field in *Accueil → Slice Zone → Partenaires → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].partners.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → Partenaires → Items*
 */
export interface HomepageDocumentDataBodyPartnersSliceItem {
	/**
	 * Nom du partenaire field in *Accueil → Slice Zone → Partenaires → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].partners.items.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Logo field in *Accueil → Slice Zone → Partenaires → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].partners.items.logo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * Site web field in *Accueil → Slice Zone → Partenaires → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].partners.items.url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyPartnersSlice = prismic.Slice<"partners", Simplify<HomepageDocumentDataBodyPartnersSlicePrimary>, Simplify<HomepageDocumentDataBodyPartnersSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → En savoir plus → Primary*
 */
export interface HomepageDocumentDataBodyEnSavoirPlusSlicePrimary {
	/**
	 * Titre de section field in *Accueil → Slice Zone → En savoir plus → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].en_savoir_plus.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *Accueil → Slice Zone → En savoir plus → Items*
 */
export interface HomepageDocumentDataBodyEnSavoirPlusSliceItem {
	/**
	 * Titre field in *Accueil → Slice Zone → En savoir plus → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].en_savoir_plus.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *Accueil → Slice Zone → En savoir plus → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].en_savoir_plus.items.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Texte du lien field in *Accueil → Slice Zone → En savoir plus → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].en_savoir_plus.items.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * Lien field in *Accueil → Slice Zone → En savoir plus → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].en_savoir_plus.items.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyEnSavoirPlusSlice = prismic.Slice<"en_savoir_plus", Simplify<HomepageDocumentDataBodyEnSavoirPlusSlicePrimary>, Simplify<HomepageDocumentDataBodyEnSavoirPlusSliceItem>>

/**
 * Primary content in *Accueil → Slice Zone → CTA Final → Primary*
 */
export interface HomepageDocumentDataBodyCtaFinalSlicePrimary {
	/**
	 * Titre field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * CTA primaire - Texte field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.cta_primary_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_primary_label: prismic.KeyTextField;
	
	/**
	 * CTA primaire - Lien field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.cta_primary_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_primary_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * CTA secondaire - Texte field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.cta_secondary_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_secondary_label: prismic.KeyTextField;
	
	/**
	 * CTA secondaire - Lien field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.cta_secondary_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_secondary_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Texte de pied field in *Accueil → Slice Zone → CTA Final → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].cta_final.primary.footer_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	footer_text: prismic.KeyTextField;
}

/**
 * Slice for *Accueil → Slice Zone*
 */
export type HomepageDocumentDataBodyCtaFinalSlice = prismic.Slice<"cta_final", Simplify<HomepageDocumentDataBodyCtaFinalSlicePrimary>, never>

type HomepageDocumentDataBodySlice = HomepageDocumentDataBodyHeroSlice | HomepageDocumentDataBodyProgrammesSlice | HomepageDocumentDataBodyMissionsSlice | HomepageDocumentDataBodyImpactSlice | HomepageDocumentDataBodyStepsSlice | HomepageDocumentDataBodyTestimonialsSlice | HomepageDocumentDataBodyFaqSlice | HomepageDocumentDataBodyPartnersSlice | HomepageDocumentDataBodyEnSavoirPlusSlice | HomepageDocumentDataBodyCtaFinalSlice

/**
 * Content for Accueil documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Accueil*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<HomepageDocumentDataBodySlice>;/**
	 * Meta Title field in *Accueil*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Titre SEO de la page d'accueil
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Accueil*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Description SEO
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Accueil*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Accueil document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Titre field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Sous-titre (optionnel) field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Image hero (optionnel) field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.hero_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	hero_image: prismic.ImageField<never>;
	
	/**
	 * Contenu field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Page legale documents
 */
interface PageLegaleDocumentData {
	/**
	 * Titre de la page field in *Page legale*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_legale.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Contenu field in *Page legale*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_legale.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;/**
	 * Meta Title field in *Page legale*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_legale.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Page legale*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_legale.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
}

/**
 * Page legale document from Prismic
 *
 * - **API ID**: `page_legale`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageLegaleDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageLegaleDocumentData>, "page_legale", Lang>;

/**
 * Content for Ressource documents
 */
interface RessourceDocumentData {
	/**
	 * Titre field in *Ressource*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Titre de la ressource
	 * - **API ID Path**: ressource.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Catégorie field in *Ressource*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ressource.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	category: prismic.SelectField<"Accompagnement/Insertion" | "Acces aux droits" | "Emploi/Formation" | "Logement/Mobilite" | "Sante">;
	
	/**
	 * Description field in *Ressource*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ressource.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Lien vers la ressource field in *Ressource*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ressource.url
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Image field in *Ressource*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ressource.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * ID original (migration) field in *Ressource*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ressource.original_id
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	original_id: prismic.NumberField;
}

/**
 * Ressource document from Prismic
 *
 * - **API ID**: `ressource`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RessourceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<RessourceDocumentData>, "ressource", Lang>;

export type AllDocumentTypes = ActualiteDocument | DocumentDocument | EducolabDocument | FoodtruckDocument | FresqueDocument | HomepageDocument | PageDocument | PageLegaleDocument | RessourceDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ActualiteDocument,
			ActualiteDocumentData,
			DocumentDocument,
			DocumentDocumentData,
			EducolabDocument,
			EducolabDocumentData,
			FoodtruckDocument,
			FoodtruckDocumentData,
			FoodtruckDocumentDataHighlightsItem,
			FoodtruckDocumentDataTourneeItem,
			FoodtruckDocumentDataEntreesItem,
			FoodtruckDocumentDataPlatsItem,
			FoodtruckDocumentDataDessertsItem,
			FoodtruckDocumentDataStepsItem,
			FresqueDocument,
			FresqueDocumentData,
			FresqueDocumentDataObjectivesItem,
			FresqueDocumentDataParcoursItem,
			FresqueDocumentDataSessionsItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataBodyHeroSlicePrimary,
			HomepageDocumentDataBodyProgrammesSlicePrimary,
			HomepageDocumentDataBodyProgrammesSliceItem,
			HomepageDocumentDataBodyMissionsSlicePrimary,
			HomepageDocumentDataBodyMissionsSliceItem,
			HomepageDocumentDataBodyImpactSlicePrimary,
			HomepageDocumentDataBodyImpactSliceItem,
			HomepageDocumentDataBodyStepsSlicePrimary,
			HomepageDocumentDataBodyStepsSliceItem,
			HomepageDocumentDataBodyTestimonialsSlicePrimary,
			HomepageDocumentDataBodyTestimonialsSliceItem,
			HomepageDocumentDataBodyFaqSlicePrimary,
			HomepageDocumentDataBodyFaqSliceItem,
			HomepageDocumentDataBodyPartnersSlicePrimary,
			HomepageDocumentDataBodyPartnersSliceItem,
			HomepageDocumentDataBodyEnSavoirPlusSlicePrimary,
			HomepageDocumentDataBodyEnSavoirPlusSliceItem,
			HomepageDocumentDataBodyCtaFinalSlicePrimary,
			HomepageDocumentDataBodySlice,
			PageDocument,
			PageDocumentData,
			PageLegaleDocument,
			PageLegaleDocumentData,
			RessourceDocument,
			RessourceDocumentData,
			AllDocumentTypes
		}
	}
}